/* Section renderers shared by the ten page versions. Every renderer returns HTML on DS markup. */
module.exports = (C, ic, il) => {
  const btn = (label, style, intent, size) => `<a class="hb-btn" href="#" data-intent="${intent || 'primary'}" data-style="${style}" data-size="${size || 'lg'}"><span class="hb-btn__label">${label}</span></a>`;
  const ctas = (cls) => `<div class="ctas ${cls || ''}">${btn(C.cta.buyer, 'filled')}${btn(C.cta.supplier, 'outlined')}</div>`;
  const eyebrow = t => `<span class="eyebrow">${t}</span>`;
  const head = (n, title, lede, cls) => `<div class="sec__head ${cls || ''}">${n ? eyebrow(n) : ''}<h2 class="sec__title">${title}</h2>${lede ? `<p class="sec__lede">${lede}</p>` : ''}</div>`;
  const checklist = items => `<ul class="checks">${items.map(i => `<li><span class="checks__dot">${ic('check')}</span><span>${i}</span></li>`).join('')}</ul>`;
  const icon = n => `<span class="ico">${ic(n)}</span>`;

  /* ---- heroes ---- */
  const heroSplit = () => `<section class="hero hero--split"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</div><div class="hero__art" aria-hidden="true">${il('welcome', 'lg')}</div></section>`;
  const heroShort = () => `<section class="hero hero--short">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas('ctas--center')}</section>`;
  const heroTwo = () => `<section class="hero hero--two"><div class="hero__top">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1></div><div class="duo">
    <div class="duo__card duo__card--buyer">${icon('cart')}<h2 class="duo__title">${C.both.buyers.title}</h2><p class="duo__lede">${C.hero.buyerLine}</p>${checklist(C.both.buyers.items.slice(0, 3))}${btn(C.cta.buyer, 'filled')}</div>
    <div class="duo__card duo__card--supplier">${icon('store')}<h2 class="duo__title">${C.both.suppliers.title}</h2><p class="duo__lede">${C.hero.supplierLine}</p>${checklist(C.both.suppliers.items.slice(0, 3))}${btn(C.cta.supplier, 'outlined')}</div></div></section>`;
  const heroExplainer = () => `<section class="hero hero--explain"><div class="read">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.what.question}</h1><p class="hero__lede">${C.what.p1}</p><blockquote class="pull">${C.what.p2}</blockquote>${ctas()}</div></section>`;
  const pcard = ([name, sup, price]) => `<article class="hb-pcard"><div class="hb-pcard__media"><span class="pcard-ph">${il('empty-products', 'sm', 'neutral')}</span></div><div class="hb-pcard__body"><span class="hb-pcard__title">${name}</span><div class="hb-pcard__row hb-pcard__price"><span class="hb-pcard__price-label">Price</span><span class="hb-pcard__price-value"><span class="hb-pcard__amount"><span class="hb-pcard__currency">BHD</span><span class="hb-pcard__figure">${price}</span></span></span></div><span class="hb-pcard__supplier">${ic('store')}<span class="hb-pcard__supplier-name">${sup}</span></span><div class="hb-pcard__actions">${btn('Add to cart', 'filled', 'primary', 'sm')}</div></div></article>`;
  const heroProduct = () => `<section class="hero hero--product"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.buyerLine}</p>${ctas()}</div>
    <div class="device" aria-label="The HIGHBASE marketplace (sample catalogue)"><div class="device__bar"><span class="device__logo">HIGHBASE</span><span class="device__search">${ic('search')}<span>Search by name, category or brand</span></span></div><div class="device__grid">${C.sample.map(pcard).join('')}</div></div></section>`;
  const heroReasons = () => `<section class="hero hero--reasons"><div class="hero__top">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.why.title}</h1><p class="hero__lede">${C.hero.lede}</p></div><ol class="reasons">${C.why.items.map(([i, t, d, f], n) => `<li class="reason"><span class="reason__n">0${n + 1}</span><div class="reason__body"><h2 class="reason__title">${t}</h2><p>${d}</p><span class="fact">${ic('check')}${f}</span></div></li>`).join('')}</ol>${ctas()}</section>`;
  const heroDark = () => `<section class="hero hero--dark"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</div><div class="hero__art" aria-hidden="true">${il('welcome', 'lg')}</div></section>`;
  const heroRegion = () => `<section class="hero hero--region"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</div>
    <div class="region"><span class="region__pin">${ic('location')}</span><span class="region__label">${C.contact.eyebrow} · Headquarters</span><span class="region__big">Bahrain</span><span class="region__addr">${C.contact.company}<br>${C.contact.address}</span><ul class="region__rows"><li>${ic('globe')}<span>Serving the Gulf’s local trade</span></li><li>${ic('phone')}<span>${C.contact.phone}</span></li><li>${ic('mail')}<span>${C.contact.email}</span></li></ul></div></section>`;
  const heroBento = () => `<section class="hero hero--bento"><div class="bento">
    <div class="bento__tile bento__tile--main">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</div>
    <div class="bento__tile bento__tile--art" aria-hidden="true">${il('welcome', 'md')}</div>
    <div class="bento__tile bento__tile--trust"><span class="tile__name">${C.trust.title}</span><ul class="mini-facts">${C.trust.items.map(([v, l]) => `<li><b>${v}</b><span>${l}</span></li>`).join('')}</ul></div>
    <div class="bento__tile"><span class="tile__name">${C.who.title}</span><ul class="mini-list">${C.who.items.map(([i, t]) => `<li>${ic(i)}<span>${t}</span></li>`).join('')}</ul></div>
    <div class="bento__tile"><span class="tile__name">${C.why.title}</span><ul class="mini-list">${C.why.items.map(([i, t]) => `<li>${ic(i)}<span>${t}</span></li>`).join('')}</ul></div>
    <div class="bento__tile"><span class="tile__name">${C.how.title}</span><ol class="mini-steps">${C.how.buyers.steps.map(([t, d], n) => `<li><span class="step__n">0${n + 1}</span><span><b>${t}</b> ${d}</span></li>`).join('')}</ol></div>
  </div></section>`;

  /* ---- bands and sections ---- */
  const trust = tone => `<section class="trust trust--${tone || 'dark'}" aria-label="${C.trust.title}"><ul class="trust__row">${C.trust.items.map(([v, l]) => `<li class="stat"><span class="stat__v">${v}</span><span class="stat__l">${l}</span></li>`).join('')}</ul></section>`;
  const what = n => `<section class="sec"><div class="sec__grid sec__grid--2">${head(n, C.what.title)}<div class="prose"><p>${C.what.p1}</p><div class="callout">${ic('info')}<span>${C.what.p2}</span></div></div></div></section>`;
  const who = (n, cls) => `<section class="sec sec--tint ${cls || ''}">${head(n, C.who.title)}<ul class="tiles" role="list">${C.who.items.map(([i, t, d]) => `<li class="tile">${icon(i)}<span class="tile__name">${t}</span>${d ? `<span class="tile__text">${d}</span>` : ''}</li>`).join('')}</ul></section>`;
  const steps = (title, items) => `<div class="hb-card steps"><h3 class="steps__title">${title}</h3><ol class="steps__list">${items.map(([t, d], i) => `<li class="step"><span class="step__n">0${i + 1}</span><span class="step__body"><b>${t}</b><span>${d}</span></span></li>`).join('')}</ol></div>`;
  const how = n => `<section class="sec">${head(n, C.how.title, C.how.lede)}<div class="sec__grid sec__grid--2">${steps(C.how.buyers.title, C.how.buyers.steps)}${steps(C.how.suppliers.title, C.how.suppliers.steps)}</div></section>`;
  const journey = n => `<section class="sec sec--tint">${head(n, C.how.title, C.how.lede, 'sec__head--center')}<ol class="journey">${C.how.nodes.map((node, i) => `<li class="jnode"><span class="jnode__dot">${i + 1}</span><span class="jnode__title">${node}</span><div class="jnode__side"><span class="jnode__who">${ic('cart')}Buyers</span><span>${C.how.buyers.steps[i][1]}</span></div><div class="jnode__side"><span class="jnode__who">${ic('store')}Suppliers</span><span>${C.how.suppliers.steps[i][1]}</span></div></li>`).join('')}</ol></section>`;
  const why = (n, facts) => `<section class="sec">${head(n, C.why.title)}<ul class="whys" role="list">${C.why.items.map(([i, t, d, f]) => `<li class="why">${icon(i)}<b>${t}</b><span>${d}</span>${facts ? `<span class="fact">${ic('check')}${f}</span>` : ''}</li>`).join('')}</ul></section>`;
  const both = n => `<section class="sec sec--tint">${head(n, C.both.title)}<div class="sec__grid sec__grid--2">${[C.both.buyers, C.both.suppliers].map(s => `<div class="hb-card side">${icon(s.icon)}<h3 class="side__title">${s.title}</h3><p class="side__lede">${s.lede}</p>${checklist(s.items)}</div>`).join('')}</div><p class="note">${C.both.note}</p></section>`;
  const global = n => `<section class="sec sec--global" hidden><div class="sec__head">${eyebrow(`${n} · <span class="hb-chip" data-style="tonal" data-size="sm"><span class="hb-chip__label">${C.global.badge}</span></span>`)}<h2 class="sec__title">${C.global.title}</h2><p class="sec__lede">${C.global.lede}</p></div><div class="sec__grid sec__grid--2">${[C.global.buy, C.global.sell].map(g => `<div class="hb-card side">${icon('globe')}<h3 class="side__title">${g.title}</h3><p class="side__lede">${g.text}</p></div>`).join('')}</div></section>`;
  const finalCta = tone => `<section class="cta cta--${tone || 'dark'}"><h2 class="cta__title">${C.final.title}</h2><p class="cta__lede">${C.final.lede}</p>${ctas('ctas--center')}</section>`;
  const contact = () => `<section class="sec contact"><div class="sec__grid sec__grid--2">${head(C.contact.eyebrow, C.contact.title, `${C.contact.company}, ${C.contact.address}.`)}<ul class="contact__rows"><li>${icon('location')}<span><b>Address</b><span>${C.contact.company}, ${C.contact.address}</span></span></li><li>${icon('phone')}<span><b>Phone</b><span>${C.contact.phone}</span></span></li><li>${icon('mail')}<span><b>Email</b><span>${C.contact.email}</span></span></li><li>${icon('message')}<span><b>${C.contact.message}</b><span>We reply during Bahrain business hours.</span></span></li></ul></div></section>`;
  const sticky = () => `<div class="stickybar">${btn(C.cta.buyer, 'filled', 'primary', 'md')}${btn(C.cta.supplier, 'outlined', 'primary', 'md')}</div>`;

  /* ---- options 11–16 (Rylo · Column · Moneda) ---- */
  const heroMission = () => `<section class="hero hero--mission">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas('ctas--center')}<div class="strip" aria-hidden="true"><div class="strip__cell">${il('welcome', 'md')}</div><div class="strip__cell">${il('empty-orders', 'md')}</div><div class="strip__cell">${il('success', 'md')}</div></div></section>`;
  const values = n => `<section class="sec">${head(n, C.why.title)}<ul class="values">${C.why.items.map(([i, t, d, f]) => `<li class="value"><h3 class="value__title">${icon(i)}${t}</h3><div class="value__body"><p>${d}</p><span class="fact">${ic('check')}${f}</span></div></li>`).join('')}</ul></section>`;
  const split1 = t => { const m = /^(.*?[.!?])\s+(.*)$/.exec(t); return m ? [m[1], m[2]] : [t, '']; };
  const declare = (text) => { const [big, rest] = split1(text); return `<section class="declare"><p class="declare__big">${big}</p>${rest ? `<p class="declare__rest">${rest}</p>` : ''}</section>`; };
  const whatPlain = n => `<section class="sec"><div class="sec__grid sec__grid--2">${head(n, C.what.title)}<div class="prose"><p>${C.what.p1}</p></div></div></section>`;
  const heroStatement = () => `<section class="hero hero--statement">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</section>`;
  const ledger = (n, title, body, lede) => `<section class="sec ledger-sec"><div class="ledger">${head(n, title, lede)}<div class="ledger__body">${body}</div></div></section>`;
  const factsList = () => `<ul class="facts">${C.trust.items.map(([v, l]) => `<li><b>${v}</b><span>${l}</span></li>`).join('')}</ul>`;
  const tilesOnly = () => `<ul class="tiles" role="list">${C.who.items.map(([i, t, d]) => `<li class="tile">${icon(i)}<span class="tile__name">${t}</span>${d ? `<span class="tile__text">${d}</span>` : ''}</li>`).join('')}</ul>`;
  const whysOnly = () => `<ul class="whys" role="list">${C.why.items.map(([i, t, d, f]) => `<li class="why">${icon(i)}<b>${t}</b><span>${d}</span><span class="fact">${ic('check')}${f}</span></li>`).join('')}</ul>`;
  const stepsOnly = () => `<div class="sec__grid sec__grid--2">${steps(C.how.buyers.title, C.how.buyers.steps)}${steps(C.how.suppliers.title, C.how.suppliers.steps)}</div>`;
  const bothOnly = () => `<div class="sec__grid sec__grid--2">${[C.both.buyers, C.both.suppliers].map(s => `<div class="hb-card side">${icon(s.icon)}<h3 class="side__title">${s.title}</h3><p class="side__lede">${s.lede}</p>${checklist(s.items)}</div>`).join('')}</div><p class="note">${C.both.note}</p>`;
  const heroSnapshots = () => `<section class="hero hero--snaps"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas()}</div><ul class="snaps" aria-label="${C.who.title}">${C.who.items.map(([i, t]) => `<li class="snap"><span class="snap__photo">${ic(i)}</span><span class="snap__cap">${t}</span></li>`).join('')}</ul></section>`;
  const pillars = () => `<div class="pillars">${C.why.items.slice(0, 3).map(([i, t, d, f], n) => `<div class="pillar"><span class="eyebrow">0${n + 1}</span>${icon(i)}<h2 class="pillar__title">${t}</h2><p>${d}</p><span class="fact">${ic('check')}${f}</span></div>`).join('')}</div>`;
  const heroPillars = () => `<section class="hero hero--pillars">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.lede}</p>${ctas('ctas--center')}${pillars()}</section>`;
  const pillarsSec = n => `<section class="sec sec--tint">${head(n, C.why.title)}${pillars()}</section>`;
  const heroApp = () => `<section class="hero hero--app"><div class="hero__text">${eyebrow(C.hero.eyebrow)}<h1 class="hero__title">${C.hero.title}</h1><p class="hero__lede">${C.hero.buyerLine}</p><div class="ctas">${btn(C.cta.buyer, 'filled')}${btn(C.cta.supplier, 'outlined')}<a class="hb-btn" href="#" data-intent="primary" data-style="tonal" data-size="lg"><span class="hb-btn__icon">${ic('download')}</span><span class="hb-btn__label">Download Our App Now</span></a></div></div>
    <div class="phone" aria-label="The HIGHBASE app (sample catalogue)"><div class="phone__bar"><span class="device__logo">HIGHBASE</span>${ic('cart')}</div><div class="phone__search">${ic('search')}<span>Search</span></div><ul class="phone__rows">${C.sample.map(([name0, sup, price]) => { const name = name0.split(' · ')[0]; return `<li><span class="phone__thumb">${ic('package')}</span><span class="phone__text"><b>${name}</b><span>${sup}</span></span><span class="phone__price">BHD ${price}</span></li>`; }).join('')}</ul></div></section>`;

  return { heroMission, values, declare, whatPlain, heroStatement, ledger, factsList, tilesOnly, whysOnly, stepsOnly, bothOnly, heroSnapshots, heroPillars, pillarsSec, heroApp, heroSplit, heroShort, heroTwo, heroExplainer, heroProduct, heroReasons, heroDark, heroRegion, heroBento, trust, what, who, how, journey, why, both, global, finalCta, contact, sticky };
};
