// 26 findings from the heuristic evaluation, with the business consequence
// each one carries — the framing a CEO reads, not the heuristic label.
module.exports = [
// ---- CART ----
{id:"C1", sec:"cart", sev:4, h:["5 · Error prevention","9 · Recover from errors"],
 title:"The cart sells stock that isn't there",
 today:"An item flagged “Only 1 item in stock” keeps a quantity of 7, and the line still totals BHD 7.000. Nothing reconciles the two.",
 ev:"Cart — Nadec Vanilla Flavored Milk 125ml.",
 fixed:"The line states the conflict, suppresses its total, and offers a one-tap “Reduce to 1” alongside a restock alert.",
 cost:"The shortfall surfaces after payment. Every occurrence becomes a refund, a substitution call, or a cancelled line."},

{id:"C2", sec:"cart", sev:4, h:["1 · Visibility of system status"],
 title:"A BHD 10 delivery fee appears one page too late",
 today:"Order Summary shows Subtotal BHD 11.000 and Total BHD 11.000. The delivery fee — 91% of the basket value — only appears on the review page.",
 ev:"Cart summary vs. review page.",
 fixed:"Delivery, coupons and VAT are itemised in the cart. No figure changes between screens.",
 cost:"Unexpected shipping cost is the most-cited reason buyers abandon a basket. Here it nearly doubles the bill without warning."},

{id:"C3", sec:"cart", sev:3, h:["2 · Match the real world","6 · Recognition over recall"],
 title:"The cart ignores supplier boundaries",
 today:"A flat product grid, though minimum order, delivery fee, coupons and dispatch all belong to a supplier. The review page then splits the order anyway.",
 ev:"Five items, no supplier boundary shown.",
 fixed:"Items sit in supplier groups carrying that supplier's terms, subtotal, delivery and readiness to order.",
 cost:"Buyers cannot predict what they will pay or when it arrives, so they call the team to find out."},

{id:"C4", sec:"cart", sev:3, h:["8 · Aesthetic and minimalist design"],
 title:"The same warning, repeated four times",
 today:"“Minimum order for this product supplier: BHD 10.000. Add BHD 6.000 more or other items to proceed.” is repeated verbatim on every card in the group.",
 ev:"Four identical blocks in one viewport.",
 fixed:"One progress bar per supplier: amount reached, target, the exact gap, and a link that closes it.",
 cost:"Repetition trains buyers to ignore the message, so the minimum blocks them at checkout instead of guiding them to a bigger basket."},

{id:"C5", sec:"cart", sev:3, h:["6 · Recognition over recall","7 · Flexibility and efficiency"],
 title:"No price per piece",
 today:"“18pcs” sits beside “BHD 1.000” with no per-piece figure. Comparing pack sizes is manual arithmetic, on every line.",
 ev:"Nadec Long Life Low Fat UHT Milk 200ml 18pcs.",
 fixed:"Every line shows price per case, price per piece, and the total piece count.",
 cost:"Cost per unit is how trade buyers decide. Making them compute it sends them to a competitor's catalogue to compare."},

{id:"C6", sec:"cart", sev:3, h:["3 · User control and freedom"],
 title:"One short supplier stalls the whole basket",
 today:"A supplier under its minimum blocks everything. The only routes out are buying more or deleting items.",
 ev:"Cart total falls from BHD 11.000 to BHD 4.000 as items are removed to get under way.",
 fixed:"Suppliers that are ready check out now. The rest stays in the cart, named beneath the button.",
 cost:"A blocked basket defers all of the revenue instead of banking the part that was already ready to ship."},

{id:"C7", sec:"cart", sev:2, h:["1 · Visibility of system status"],
 today:"Deselecting items changes the header total silently. Nothing states which lines the order actually covers.",
 title:"Partial selection changes the total silently",
 ev:"“Select All” and per-card checkboxes.",
 fixed:"The summary counts the lines it covers, and each supplier group reads “Ready to order” or “Excluded from this order”.",
 cost:"Buyers place an order missing lines, then place a second one — doubling the handling for a single restock."},

{id:"C8", sec:"cart", sev:2, h:["7 · Flexibility and efficiency"],
 title:"No way to reorder",
 today:"There is no reorder, no saved list and no SKU entry anywhere in the flow. Every order starts from browsing.",
 ev:"Observed across the full walkthrough.",
 fixed:"Quick-add by SKU, “Save as list”, and a recurring-basket prompt on the confirmation screen.",
 cost:"B2B demand is repetitive. Charging a full browse for every repeat order is where regular buyers quietly churn."},

// ---- REVIEW ----
{id:"R1", sec:"review", sev:3, h:["4 · Consistency and standards","1 · Visibility of system status"],
 title:"“Seller Total” is not the total",
 today:"“Seller Total BHD 10.000” appears after three discounts with no order total beside it. It is unclear whether this is what will be charged.",
 ev:"Subtotal BHD 11.000, delivery BHD 10.000, three stacked discounts, then “Seller Total”.",
 fixed:"One summary with one hierarchy — items, delivery, discounts, VAT, Total — identical on all three screens.",
 cost:"The buyer cannot verify the bill before paying, so their finance team queries it afterwards."},

{id:"R2", sec:"review", sev:2, h:["2 · Match the real world"],
 title:"Discounts labelled with internal codes",
 today:"Discounts appear as “Mahmmod_Seller_code”, “jpre” and “10Dinar” — raw internal identifiers that carry no meaning for the buyer.",
 ev:"Review page, discount rows.",
 fixed:"Each discount names its source and its value: “Coupon ALMANAR2 — supplier coupon, −BHD 2.000”.",
 cost:"A discount the buyer cannot recognise earns no goodwill. The margin is given away invisibly."},

{id:"R3", sec:"review", sev:2, h:["7 · Flexibility and efficiency"],
 title:"The coupon field comes after the decision",
 today:"Coupon entry is at the very bottom of the page, beneath the totals it would change.",
 ev:"Review page, below “Seller Total”.",
 fixed:"Coupon entry sits at the top of the summary, above the figures it changes.",
 cost:"Buyers leave the page to hunt for a code, or abandon believing none applies to them."},

// ---- ADDRESS & DOCUMENTS ----
{id:"A1", sec:"addr", sev:4, h:["1 · Visibility of system status"],
 title:"No order summary at the moment of commitment",
 today:"The page carries no order summary and no total. The buyer presses “Place Order” with nothing on screen saying what is being bought, or for how much.",
 ev:"Full page: verification header, branch details, address, documents, button.",
 fixed:"A sticky summary with the full breakdown, present on every checkout screen and beside the button itself.",
 cost:"This is the riskiest moment in the flow. Buyers hesitate, navigate back to re-check, and lose the basket doing it."},

{id:"A2", sec:"addr", sev:4, h:["7 · Flexibility and efficiency","3 · User control and freedom"],
 title:"Trade documents are demanded on every order",
 today:"CR number, commercial licence and personal ID are uploaded inside the order — on every purchase, including routine repeat ones.",
 ev:"Business Documents section, above “Place Order”.",
 fixed:"Verification moves to the account. Checkout shows a verified chip with CR, VAT and expiry. Unverified buyers still order — dispatch waits, not the order.",
 cost:"This taxes precisely the customers who buy most often. A document wall between a repeat buyer and a routine restock is the most expensive friction in the product."},

{id:"A3", sec:"addr", sev:4, h:["8 · Aesthetic and minimalist design","1 · Visibility of system status"],
 title:"The uploaded ID takes over the page",
 today:"The uploaded ID renders full-bleed at its natural size, pushing “Place Order” thousands of pixels below the fold. A larger file pushes it further still.",
 ev:"Screenshot 1 — the image fills the viewport and continues past it.",
 fixed:"Attachments render as fixed-height rows: thumbnail, name, size, preview, remove. User content never sets page height.",
 cost:"The buy button becomes unreachable without a long scroll past the buyer's own ID photo."},

{id:"A4", sec:"addr", sev:3, h:["1 · Visibility of system status","4 · Consistency and standards"],
 title:"No real progress indicator",
 today:"A panel labelled “Step / Address & Documents” sits above the fold; a separate “Step 2” chip sits further down. Neither says how many steps exist.",
 ev:"Two competing step markers on one page.",
 fixed:"One indicator with three counted steps: Cart → Delivery & purchase details → Payment.",
 cost:"Buyers who cannot see the end of a process assume it is longer than it is, and stop before reaching it."},

{id:"A5", sec:"addr", sev:3, h:["4 · Consistency and standards"],
 title:"Settled values are styled as warnings",
 today:"Field values are set in orange on white — Bahrain, Manama, 18, 11111 — at a measured contrast of 2.03:1. Orange elsewhere in the interface means “warning”.",
 ev:"Screenshots 1 and 2, Delivery Address.",
 fixed:"Values in near-black at 17.2:1. Amber is reserved for genuine attention states; the palette is audited to 4.5:1 minimum.",
 cost:"Below the WCAG AA threshold for body text — an accessibility and procurement-compliance exposure, and buyers click values that are not links."},

{id:"A6", sec:"addr", sev:3, h:["1 · Visibility of system status"],
 title:"“Place Order” carries no amount",
 today:"The commit button states no amount, and no amount is visible anywhere else on the page.",
 ev:"Screenshot 3, Business Documents footer.",
 fixed:"The button reads “Place order · BHD 11.000”.",
 cost:"The cheapest reassurance available in any checkout, currently unspent."},

{id:"A7", sec:"addr", sev:3, h:["1 · Visibility of system status","2 · Match the real world"],
 title:"No delivery date or window",
 today:"No delivery date, time window or shipment count is offered or shown, even though the order will split by supplier.",
 ev:"Address confirmation, full page.",
 fixed:"Day and time-slot pickers per shipment, with capacity shown and the shipment count stated up front.",
 cost:"Businesses staff their goods-in bay. An unscheduled delivery fails, and a failed delivery is paid for twice."},

{id:"A8", sec:"addr", sev:3, h:["2 · Match the real world"],
 title:"None of the fields procurement runs on",
 today:"No purchase order number, no cost centre, no invoice recipient — the fields a buyer's finance team reconciles against.",
 ev:"Branch Details and Delivery Address sections.",
 fixed:"Optional PO number, cost centre and invoice email, stated as printed on the tax invoice.",
 cost:"Without them the buyer re-keys every order into their own system. That is the fastest way to lose a corporate account."},

{id:"A9", sec:"addr", sev:2, h:["8 · Aesthetic and minimalist design","10 · Help and documentation"],
 title:"An empty VAT panel",
 today:"“Have VAT certificate” is an unchecked box beside a large empty panel — roughly a third of the section is blank, with no explanation of what checking it does.",
 ev:"Screenshot 1, Business Documents.",
 fixed:"VAT status is part of the account verification line, stated as a value rather than an empty container.",
 cost:"Buyers skip it, and VAT-reclaim data never reaches the invoice that needs it."},

{id:"A10", sec:"addr", sev:2, h:["1 · Visibility of system status"],
 title:"A map pin that confirms nothing",
 today:"The pin is required but never resolved back to anything. There is no confirmation of the address it corresponds to, and no way to tell a correct pin from a default one.",
 ev:"Select Address Location, address confirmation.",
 fixed:"The pin shows its saved coordinates, is labelled as what drivers actually use, and is adjustable in place.",
 cost:"Wrong pins mean wrong drops, and that cost lands on the delivery team rather than the buyer."},

// ---- CONFIRMATION ----
{id:"P1", sec:"pay", sev:4, h:["7 · Flexibility and efficiency","10 · Help and documentation"],
 title:"Payment has to be finished on another page",
 today:"“Click on Track Your Order to upload the transaction receipt” — the page that creates the payment task sends the buyer elsewhere to complete it.",
 ev:"Screenshot 4, beneath the bank details.",
 fixed:"The receipt dropzone sits directly under the bank details, with “I'll pay later” as the explicit alternative.",
 cost:"Every hop between a task and its completion loses people — and this hop sits between the order and the money."},

{id:"P2", sec:"pay", sev:3, h:["1 · Visibility of system status","4 · Consistency and standards"],
 title:"“Placed successfully” while still unpaid",
 today:"“Your order has been placed successfully” appears while payment is outstanding — two contradictory states on one screen.",
 ev:"Screenshot 4, page header vs. payment panel.",
 fixed:"“Order received”, with the outstanding payment as the most prominent card and the current stage marked on a status timeline.",
 cost:"Buyers believe they are done and never transfer. The order ages in the queue until somebody chases it by hand."},

{id:"P3", sec:"pay", sev:3, h:["1 · Visibility of system status"],
 title:"No payment deadline",
 today:"No deadline, no reservation window, and no stated consequence of not transferring the amount.",
 ev:"Screenshot 4, HIGHBASE Payment panel.",
 fixed:"A named expiry with a live countdown, and the stock-reservation rule stated in the first sentence.",
 cost:"A manual transfer with no deadline becomes “later”. Stock sits reserved against orders that will never pay."},

{id:"P4", sec:"pay", sev:3, h:["1 · Visibility of system status","10 · Help and documentation"],
 title:"The page ends at the bank details",
 today:"No delivery date, no next steps, and no route to the supplier. The confirmation stops once the IBAN is on screen.",
 ev:"Screenshot 4, full page.",
 fixed:"A dated timeline through to invoicing, plus track, proforma download and message-supplier actions.",
 cost:"“When does my stock arrive?” becomes a support ticket on essentially every order."},

{id:"P5", sec:"pay", sev:2, h:["10 · Help and documentation"],
 title:"No transfer reference given",
 today:"The transfer reference is never stated, so a buyer paying from their banking app has no instruction on how the payment will be matched to the order.",
 ev:"Screenshot 4, Bank Details.",
 fixed:"The reference is a copyable field of its own, with the matching rule stated directly beneath it.",
 cost:"Unmatched transfers are reconciled by hand, by finance, one payment at a time."}
];
