
  /* ============================================================
     Shared pieces — the same data, drawn once, reused by all three versions.
     ============================================================ */

  /* A value the buyer has to carry into a banking app: shown whole, and copyable.
     The clipboard is not available on every origin, so a failure is reported. */
  function copyRow(label, value, o){
    o = o || {};
    return '<div class="copyrow"' + (o.strong ? ' data-strong' : '') + '>' +
      '<dt class="hb-body-sm">' + label + '</dt>' +
      '<dd class="' + (o.big ? 'hb-headline-sm' : 'hb-body-md') + ' num">' + esc(o.display || value) + '</dd>' +
      iconBtn(I.copy, "Copy " + label, { style: "ghost", size: "sm",
        attrs: ' data-act="copy" data-value="' + esc(value) + '" data-label="' + esc(label.toLowerCase()) + '"' }) +
      '</div>';
  }
  function bankRows(){
    var b = state.bank;
    return '<dl class="copyrows">' +
      copyRow("Account name", b.holder) +
      copyRow("IBAN", b.iban, { display: group(b.iban) }) +
      copyRow("SWIFT / BIC", b.swift) +
    '</dl>';
  }
  function copyAllBtn(){
    var b = state.bank, t = state.order;
    var all = b.holder + "\n" + b.iban + "\n" + b.swift + "\n" + bhd(t.total) + "\nReference: " + t.ref;
    return btn("Copy all details", { style: "outlined", size: "md", icon: I.copy,
      attrs: ' data-act="copy" data-value="' + esc(all) + '" data-label="bank details"' });
  }

  /* The QR is generated by the payment service from the same IBAN and amount. The
     prototype cannot generate a scannable code and does not fake one: the frame is
     drawn at its real size and says what it is. (proposal — placeholder) */
  function qrBlock(o){
    o = o || {};
    return '<div class="qr' + (o.size === "lg" ? " qr--lg" : "") + '">' +
      (o.title ? '<span class="hb-title-sm">' + o.title + '</span>' : '') +
      '<div class="qr__code" role="img" aria-label="Payment QR code, generated by the bank service">' +
        '<span class="qr__ph hb-label-md">QR placeholder</span>' +
      '</div>' +
      '<span class="hb-body-sm muted">Scan from your bank app to open the transfer with the amount and reference already filled.</span>' +
      '<span class="hb-label-sm muted">The live code is generated by the payment service — this frame is its size, not a scannable code.</span>' +
    '</div>';
  }

  /* The amount is the one number the buyer acts on, so it is the largest thing on
     every version and always carries its own copy button. */
  function amountBlock(o){
    o = o || {};
    return '<div class="amount"' + (o.tone ? ' data-tone="' + o.tone + '"' : '') + '>' +
      '<div class="amount__lines">' +
        '<span class="hb-label-md">' + (o.label || "Amount to transfer") + '</span>' +
        /* the system ships display-lg and the headline roles; there is no display-sm, and
           none is invented here — headline-lg is the largest role this page can use */
        '<span class="hb-headline-lg num">' + bhd(state.order.total) + '</span>' +
        '<span class="hb-body-sm">Reference <span class="num">' + esc(state.order.ref) + '</span> — put it in the transfer note.</span>' +
      '</div>' +
      iconBtn(I.copy, "Copy the amount", { style: "outlined", size: "md",
        attrs: ' data-act="copy" data-value="' + state.order.total.toFixed(3) + '" data-label="amount"' }) +
    '</div>';
  }

  /* The receipt upload. One zone, four states: ready, refused, uploading, uploaded. */
  function receiptZone(o){
    o = o || {};
    if (state.uploading) {
      return '<div class="hb-upload" data-state="uploading"><div class="hb-upload__files"><div class="hb-upload__file">' +
        '<span class="receipt-prev">' + I.file + '</span>' +
        '<div class="hb-upload__file-meta"><span class="hb-upload__name">' + esc(state.uploadName || "Uploading…") + '</span>' +
        '<span class="hb-upload__size">Uploading…</span>' +
        '<span class="hb-upload__bar"><i class="upzone__bar"></i></span></div></div></div></div>';
    }
    if (state.receipt) {
      var f = state.receipt;
      return '<div class="hb-upload" data-state="uploaded"><div class="hb-upload__files"><div class="hb-upload__file">' +
        '<span class="receipt-prev" aria-hidden="true">' + (f.url && f.isImage ? '<img src="' + f.url + '" alt="">' : I.file) + '</span>' +
        '<div class="hb-upload__file-meta"><span class="hb-upload__name">' + esc(f.name) + '</span>' +
        '<span class="hb-upload__size"><span class="num">' + esc(f.size) + '</span> · sent just now</span></div>' +
        '<div class="row">' + btn("Preview", { style: "ghost", size: "sm", icon: I.view, attrs: ' data-act="view-receipt"' }) +
          btn("Replace", { style: "outlined", size: "sm", icon: I.refresh, attrs: ' data-act="pick-receipt"' }) +
          iconBtn(I.close, "Remove the receipt", { intent: "danger", attrs: ' data-act="remove-receipt"' }) +
        '</div></div></div></div>';
    }
    var e = state.error;
    return '<div class="hb-upload" data-state="' + (e ? "error" : "ready") + '" tabindex="0" role="button"' +
      ' aria-label="Upload the transfer receipt" data-act="pick-receipt" data-drop="receipt">' +
      '<span class="hb-upload__icon">' + (e ? I.error : I.upload) + '</span>' +
      '<span class="hb-upload__title">' + (e ? esc(e) : (o.title || "Upload the transfer receipt")) + '</span>' +
      '<span class="hb-upload__hint">' + (e ? "Choose another file" : "Drop the screenshot or PDF here, or click to choose") + '</span>' +
      '<span class="hb-upload__max">PDF, JPG or PNG · up to 10 MB</span></div>';
  }

  /* Where the order is now, in four states the buyer can read at a glance. The
     labels are the system's status vocabulary; the copy is the buyer's. */
  var TRACK = [
    { key: "placed",  title: "Order placed",        done: function () { return true; },
      note: function () { return state.order.placedAt; } },
    { key: "pay",     title: "Transfer the amount", done: function () { return state.transferred || paid(); },
      note: function () { return state.transferred || paid() ? "Marked as transferred" : bhd(state.order.total) + " to Highbase"; } },
    { key: "receipt", title: "Send the receipt",    done: function () { return paid(); },
      note: function () { return paid() ? esc(state.receipt.name) : "So we can match your transfer"; } },
    { key: "confirm", title: "Highbase confirms",   done: function () { return false; },
      note: function () { return paid() ? "Within one working day" : "After the receipt arrives"; } }
  ];
  function tracker(o){
    o = o || {};
    var firstOpen = true;
    return '<ol class="track' + (o.compact ? " track--compact" : "") + '">' + TRACK.map(function (s) {
      var done = s.done(), now = !done && firstOpen;
      if (now) { firstOpen = false; }
      return '<li data-state="' + (done ? "done" : now ? "now" : "next") + '">' +
        '<span class="track__mark">' + (done ? I.check : now ? I.clock : "") + '</span>' +
        '<span class="track__lines"><span class="hb-label-lg">' + s.title + '</span>' +
        '<span class="hb-body-sm muted">' + s.note() + '</span></span></li>';
    }).join('') + '</ol>';
  }

  /* The order line itself — the confirmation, kept quiet once it has been read. */
  function orderLine(o){
    o = o || {};
    var t = state.order;
    return '<div class="orderline' + (o.hero ? " orderline--hero" : "") + '">' +
      '<span class="orderline__mark">' + I.check + '</span>' +
      '<div class="orderline__lines">' +
        '<span class="' + (o.hero ? "hb-title-lg" : "hb-title-sm") + '">Order placed</span>' +
        '<span class="hb-body-sm muted"><span class="num">' + esc(t.ref) + '</span> · ' + esc(t.placedAt) +
          ' · ' + t.lines + ' lines from ' + esc(t.supplier) + ' · delivery ' + esc(t.delivery) + '</span>' +
      '</div>' +
      statusChip(stage().status, stage().label) +
      btn("Track order", { style: "ghost", size: "sm", attrs: ' data-act="track"' }) +
    '</div>';
  }

  /* What happens after the receipt — held back until asked for, on every version. */
  /* Checkout does not ask for the receipt (PM, 17 Sep): the buyer can add it from inside the
     order if they want to, so the page says so rather than making it a step. */
  function whatNext(o){
    o = o || {};
    return '<details class="why"><summary class="hb-body-sm">' + I.chevronDown +
        (o.label || 'What happens after I send the receipt?') + '</summary>' +
      '<div class="stack" style="margin-top:var(--hb-space-12)">' +
        '<p class="hb-body-sm">Highbase matches your transfer against this order, usually within one working day. You will get a message and the order moves to Approved — no further action from you.</p>' +
        '<p class="hb-body-sm">' + (o.receiptInOrder
          ? 'If you want to send the receipt, add it from the order itself — this page does not ask for it. Anything missing, we message you on the order rather than emailing.'
          : 'If anything is missing we message you on this order rather than emailing, so the whole exchange stays in one place.') + '</p>' +
      '</div></details>';
  }
  function paidBanner(){
    return alert("success", '<span class="hb-alert__title">Receipt received</span>' +
      '<span class="hb-alert__text">We will confirm the payment within one working day and move the order to Approved. Nothing else is needed from you.</span>',
      { kind: "hb-banner", actions: btn("Track order", { style: "outlined", size: "sm", attrs: ' data-act="track"' }) });
  }
